# Generated by Django 2.0.2 on 2018-02-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='value',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='user',
        ),
    ]
