# Generated by Django 2.0.2 on 2018-02-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_produce_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='user',
            new_name='seller',
        ),
    ]
