# Generated by Django 2.0.2 on 2018-02-19 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_produce_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
