# Generated by Django 2.0.2 on 2018-02-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180219_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produce',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
