# Generated by Django 2.0.2 on 2018-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180219_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
    ]
