# Generated by Django 2.0.2 on 2018-02-21 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('main_app', '0011_auto_20180219_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('street', models.CharField(max_length=100)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('gps_lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
