# Generated by Django 2.0.2 on 2018-02-22 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20180222_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
